packages:
  - 'packages/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': set this to true or false
  esbuild: true
  prisma: true
  sqlite3: true
  tesseract.js: set this to true or false
minimumReleaseAgeExclude:
  - tencentcloud-sdk-nodejs-ocr@4.1.288
