[build]
builder = "NIXPACKS"
buildCommand = "cd packages/server && npx prisma generate && (npx tsc --skipLibCheck || true)"

[deploy]
startCommand = "cd packages/server && node dist/app.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
