[build]
builder = "NIXPACKS"
buildCommand = "cd packages/server && npx prisma generate && (npx tsc --skipLibCheck || true)"

[deploy]
startCommand = "cd packages/server && npx prisma@5.22.0 db push --force-reset && node dist/app.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
